"""add interview focus columns

Revision ID: c5669b522b3e
Revises: 615df4d7cad3
Create Date: 2026-08-05 12:16:21.425049
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c5669b522b3e'
down_revision: str | None = '615df4d7cad3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Server defaults let these NOT NULL columns be added to a table that already has
    # rows; new sessions get their values from the ORM model defaults.
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus', sa.String(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('focus_snapshot', sa.Text(), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_column('focus_snapshot')
        batch_op.drop_column('focus')

    # ### end Alembic commands ###
